### ISSUE TITLE
wallet amount unverified after viacoin distribution

### ISSUE THREAD

**Issue by wood11** [vialectrum/vialectrum-obsolete#3]
hello,
I have a problem with my received amount, i have received 55.32772524 but they are still unverified. I looked on the blockchain aswell and there it said "not yet redeemed" .
I used the vialectrum wallet and i read that there are some bugs, is there a way that i can send them to my viacoin wallet?
Can someone help me?
Thanks wood11.

**Comment by btcdrak** [comment]
For now, just export the private key and use Viacoin-Qt http://blog.viacoin.org/2014/07/18/wallet-woes.html

**Comment by btcdrak** [comment]
Fixed in 6bedcd64 @recode

**Comment by wood11** [comment]
Hello
BIG THX, for you help.
Probely i was on the right way but i have not noticed te QT-wallet so i did
it in the vialectum wallet.
Thx for your quick repley, i appreciate your work and how the vialectum
wallet works,smart.
Let via rule!
Greetz wood11
Op 19 jul. 2014 15:29 schreef "฿tcDrak" notifications@github.com:
