### ISSUE TITLE
Vialectrum - error message when tying to send funds.

### ISSUE THREAD

**Issue by chorobes** [vialectrum/vialectrum-obsolete#6]
I am currently using Vialectrum 1.9.8.4 and get an error code anytime I try to send any funds out. The error code is " error: {u'message': u'64: non-mandatory-script-verify-flag (No error)', u'code': -26}.

Anyone have any ideas? Thank you

**Comment by romanornr** [comment]
Use TCP instead of SSL

**Comment by chorobes** [comment]
I am still receiving the same error. I hit the circle in the bottom right and change the protocol to TCP, correct? I did that and still get the same error unfortunately.

**Comment by romanornr** [comment]
We will investigate it 
cc @marshallstokes

**Comment by romanornr** [comment]
btw @chorobes have you tried to restart your pc or try another pc.
I had the same problem once.

**Comment by chorobes** [comment]
@romanornr I did restart my PC and also tried a computer that was even in another house. Update: Somestimes it lets me send 50 VIA through, but only rarely. Anything more than 50 doesn't seem to work.

Update 2: For some reason, if I can manage to open Vialectrum and then within 10-15 seconds send my funds it works without a hitch. wtf

**Comment by marshallstokes** [comment]
@romanornr thoughts on [this potential solution](https://github.com/vbuterin/pybitcointools/issues/89#issuecomment-104916051)?

**Comment by romanornr** [comment]
@marshallstokes @chorobes testing this myself now

**Comment by romanornr** [comment]
@chorobes Can you go to Tools > Network

and add & use ````viax1.bitops.me````
on TCP
After you did that. Close electrum. Open it again and try to send the transaction.

**Comment by chorobes** [comment]
I tried that and it worked. Thanks guys!

**Comment by romanornr** [comment]
I'm glad it worked @chorobes 
Also congrants you were the fist person who used the new VialectrumX server !
